### ISSUE TITLE
Dead link to the paper

### ISSUE THREAD

**Issue by ngaumont** [DAMA-UPC/SCD#3]
Hi,

The link for the corresponding paper is not working:
High quality, scalable and parallel community detection for large real graphs. Arnau Prat-Pérez, David Dominguez-Sal, Josep-Lluis Larriba-Pey - WWW 2014.

You might want to change it to :
https://www.dama.upc.edu/en/publications/fp546prat.pdf

Thanks for publishing your code.
Noé

**Comment by ArnauPrat** [comment]
Thanks! Fixed!
